Repository Quantum-Tutors/quantum-tutor, pull requests merged in 2024-09, with the labels that each got.

#10 Fix README.md (formatting)
  README.md
Labels: documentation

#12 Error boundary for App
  .gitignore
  quantum-tutor-web/app/error.tsx
  quantum-tutor-web/app/not-found.tsx
  quantum-tutor-web/package-lock.json
  quantum-tutor-web/package.json
  quantum-tutor-web/public/404-error.png
  quantum-tutor-web/tsconfig.json
Labels: UI changes

#17 Add theme and theme toggle for the app
  quantum-tutor-web/src/app/app/layout.tsx
  quantum-tutor-web/src/app/app/page.module.scss
  quantum-tutor-web/src/app/app/page.tsx
  quantum-tutor-web/src/app/app/welcome/page.module.scss
  quantum-tutor-web/src/app/app/welcome/page.tsx
  quantum-tutor-web/src/app/layout.tsx
  quantum-tutor-web/src/components/ChatContainer/ChatContainer.tsx
  quantum-tutor-web/src/components/FeatureBox/FeatureBox.tsx
  quantum-tutor-web/src/components/FeatureBoxList/FeatureBoxList.tsx
  quantum-tutor-web/src/components/LeftNav/LeftNav.tsx
  quantum-tutor-web/src/components/Loader/Loader.tsx
  quantum-tutor-web/src/components/MoreOption/MoreOption.tsx
  quantum-tutor-web/src/components/PromptField/PromptField.tsx
  quantum-tutor-web/src/components/ResponseAction/ResponseAction.tsx
  quantum-tutor-web/src/styles/FeatureBox.module.scss
  quantum-tutor-web/src/styles/GlobalTheme.ts
  quantum-tutor-web/tsconfig.json
Labels: enhancement, UI changes

#27 Added fake backend for frontend development
  llm-server/config/.env
  llm-server/data/Readme.md
  llm-server/data/convo-generator.py
  requirements.txt
Labels: Backend API changes

#33 Wiring for message API response
  llm-server/data/convo-generator.py
  quantum-tutor-web/package-lock.json
  quantum-tutor-web/package.json
  quantum-tutor-web/src/app/api/users/chat.ts
  quantum-tutor-web/src/app/app/[id]/page.tsx
  quantum-tutor-web/src/app/app/layout.tsx
  quantum-tutor-web/src/app/app/page.tsx
  quantum-tutor-web/src/components/ChatBottom/ChatBottom.tsx
  quantum-tutor-web/src/components/ChatContainer/ChatContainer.tsx
  quantum-tutor-web/src/components/Exchange/Exchange.tsx
  quantum-tutor-web/src/components/ModelResponse/ModelResponse.tsx
  quantum-tutor-web/src/components/PromptField/PromptField.tsx
  quantum-tutor-web/src/components/UserQuery/UserQuery.tsx
  quantum-tutor-web/src/styles/ChatBottom.module.scss
Labels: UI changes
